# Generated by Django 2.1.5 on 2019-02-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
